//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public long Id { get; set; }
        public string Login { get; set; }
        public System.DateTime Data { get; set; }
        public bool Statys { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
