//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScheduleEntities : DbContext
    {

        private static ScheduleEntities _context;

        public static ScheduleEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ScheduleEntities();
            }

            return _context;
        }
        public ScheduleEntities()
            : base("name=ScheduleEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<LoginHistory> LoginHistory { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleMonth> RoleMonth { get; set; }
        public virtual DbSet<RoleSheldules> RoleSheldules { get; set; }
        public virtual DbSet<Sheldules> Sheldules { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
