//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheldules
    {
        public int id { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public int idDay { get; set; }
        public int idMonth { get; set; }
    
        public virtual RoleMonth RoleMonth { get; set; }
        public virtual RoleSheldules RoleSheldules { get; set; }
    }
}
